from tkinter import *
from tkinter import messagebox
import nltk
from nltk.corpus import words
from time import gmtime, strftime
import time
from collections import Counter
nltk.download('words')
word_list =['hello','description','python','collision','beautiful','desc','apron','wonderful','pronounciation','encyclopdia','professional','king','noun','pronoun','tesla','attribute','possible','hollow','barking','method','evocation','onslaught']
Matrix_list=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y','z' ]
score=0
window=Tk()
window.title("Word Puzzle Game")
window.geometry("1300x672+0+0")
window.configure(bg="#F6B84D")
def checkspells():
    global score
    word=word_check.get()
    if word in word_list:
        dict = Counter(word)
        flag = 1
        for key in dict.keys():
            if key not in Matrix_list:
                flag = 0
        if flag == 1 and len(word) > 3:
            score=score+5
            total="score = "+str(score)
            label.configure(text=total)
            print(word)
        else:
            messagebox.showinfo("ERROR","No match was found OR word length is greater than 3")
    else:
        messagebox.showinfo("ERROR","No match")
        print("No Word")
    word_check.delete(0, 'end')
def tick(time1=''):
    time2=time.strftime("%M:%S")
    if time2!=time1:
        time1=time2
def quit_pro():
    messagebox.showinfo("Oops!!","Time Up! Your Score",+str(score))
    window.destroy()
def reset():
    word_check.delete(0,END)
    return

    
btn1 = Button(window, text="A",bg="yellow", fg="Black",activebackground='#00ff00',width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=1)
btn2 = Button(window, text="P",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20')) 
btn2.grid(column=2, row=1)
btn3 = Button(window, text="R",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=1)
btn4 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=1)
btn5 = Button(window, text="N",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=1)
btn6 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=1)
btn7 = Button(window, text="U",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=1)
btn8 = Button(window, text="N",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=1)
btn9 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=1) 
btn10 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=1)
btn11 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=1)
btn12 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=1)
btn13 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=1)
btn14 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=1)
btn15 = Button(window, text="N",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=1)


btn1 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=2)
btn2 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=2)
btn3 = Button(window, text="B",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=2)
btn4 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=2) 
btn5 = Button(window, text="U",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=2)
btn6 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=2)
btn7 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=2)
btn8 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=2)
btn9 = Button(window, text="D",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=2)
btn10 = Button(window, text="G",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=2)
btn11 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=2)
btn12 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=2)
btn13 = Button(window, text="B",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=2)
btn14 = Button(window, text="N",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=2)
btn15 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=2)


btn1 = Button(window, text="D",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=3)
btn2 = Button(window, text="S",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=3)
btn3 = Button(window, text="W",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=3)
btn4 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=3)
btn5 = Button(window, text="N",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=3)
btn6 = Button(window, text="D",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=3)
btn7 = Button(window, text="E",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=3)
btn8 = Button(window, text="R",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=3)
btn9 = Button(window, text="F",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=3)
btn10 = Button(window, text="U",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=3)
btn11 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=3)
btn12 = Button(window, text="M",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=3)
btn13 = Button(window, text="E",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=3)
btn14 = Button(window, text="S",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=3)
btn15 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=3)


btn1 = Button(window, text="E",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=4)
btn2 = Button(window, text="S",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=4)
btn3 = Button(window, text="D",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=4)
btn4 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=4)
btn5 = Button(window, text="B",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=4)
btn6 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=4)
btn7 = Button(window, text="R",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=4)
btn8 = Button(window, text="K",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=4)
btn9 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=4)
btn10 = Button(window, text="N",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=4)
btn11 = Button(window, text="G",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=4)
btn12 = Button(window, text="E",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=4)
btn13 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=4)
btn14 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=4)
btn15 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=4)

btn1 = Button(window, text="P",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=5)
btn2 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=5)
btn3 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=5)
btn4 = Button(window, text="U",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=5)
btn5 = Button(window, text="P",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=5)
btn6 = Button(window, text="Y",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=5)
btn7 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=5)
btn8 = Button(window, text="H",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=5)
btn9 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=5)
btn10 = Button(window, text="N",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=5)
btn11 = Button(window, text="U",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=5)
btn12 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=5)
btn13 = Button(window, text="U",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=5)
btn14 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=5)
btn15 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=5)

btn1 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=6)
btn2 = Button(window, text="B",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=6)
btn3 = Button(window, text="Z",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=6)
btn4 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=6)
btn5 = Button(window, text="K",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=6)
btn6 = Button(window, text="B",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=6)
btn7 = Button(window, text="E",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=6)
btn8 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=6)
btn9 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=6)
btn10 = Button(window, text="X",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=6)
btn11 = Button(window, text="D",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=6)
btn12 = Button(window, text="H",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=6)
btn13 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=6)
btn14 = Button(window, text="U",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=6)
btn15 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=6)


btn1 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=7)
btn2 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=7)
btn3 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=7) 
btn4 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=7)
btn5 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=7)
btn6 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=7)
btn7 = Button(window, text="S",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=7)
btn8 = Button(window, text="Z",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=7)
btn9 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=7)
btn10 = Button(window, text="H",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=7)
btn11 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20')) 
btn11.grid(column=11, row=7)
btn12 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=7)
btn13 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=7)
btn14 = Button(window, text="G",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=7)
btn15 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=7)


btn1 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=8)
btn2 = Button(window, text="E",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=8)
btn3 = Button(window, text="D",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=8)
btn4 = Button(window, text="W",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=8)
btn5 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=8)
btn6 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=8) 
btn7 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=8)
btn8 = Button(window, text="B",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=8)
btn9 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=8)
btn10 = Button(window, text="Y",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=8)
btn11 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=8)
btn12 = Button(window, text="D",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=8)
btn13 = Button(window, text="F",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=8)
btn14 = Button(window, text="H",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=8)
btn15 = Button(window, text="U",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=8)


btn1 = Button(window, text="Y",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=9) 
btn2 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=9)
btn3 = Button(window, text="B",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=9)
btn4 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=9)
btn5 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=9)
btn6 = Button(window, text="J",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=9)
btn7 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=9)
btn8 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=9)
btn9 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20')) 
btn9.grid(column=9, row=9)
btn10 = Button(window, text="R",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=9)
btn11 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=9)
btn12 = Button(window, text="B",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=9)
btn13 = Button(window, text="U",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=9)
btn14 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=9)
btn15 = Button(window, text="E",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=9)


btn1 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=10)
btn2 = Button(window, text="X",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=10)
btn3 = Button(window, text="D",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=10)
btn4 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=10) 
btn5 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=10)
btn6 = Button(window, text="B",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=10)
btn7 = Button(window, text="H",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=10)
btn8 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=10)
btn9 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=10)
btn10 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=10)
btn11 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=10)
btn12 = Button(window, text="W",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20')) 
btn12.grid(column=12, row=10)
btn13 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=10)
btn14 = Button(window, text="X",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=10)
btn15 = Button(window, text="K",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=10)


btn1 = Button(window, text="N",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=11)
btn2 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=11)
btn3 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=11)
btn4 = Button(window, text="D",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=11)
btn5 = Button(window, text="E",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=11)
btn6 = Button(window, text="S",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=11)
btn7 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=11) 
btn8 = Button(window, text="V",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=11)
btn9 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=11)
btn10 = Button(window, text="P",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn10.grid(column=10, row=11)
btn11 = Button(window, text="Y",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=11)
btn12 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=11)
btn13 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=11)
btn14 = Button(window, text="N",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=11)
btn15 = Button(window, text="Z",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=11)


btn1 = Button(window, text="E",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn1.grid(column=1, row=12)
btn2 = Button(window, text="C",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn2.grid(column=2, row=12) 
btn3 = Button(window, text="L",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn3.grid(column=3, row=12)
btn4 = Button(window, text="A",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn4.grid(column=4, row=12)
btn5 = Button(window, text="N",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn5.grid(column=5, row=12)
btn6 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn6.grid(column=6, row=12)
btn7 = Button(window, text="I",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn7.grid(column=7, row=12)
btn8 = Button(window, text="T",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn8.grid(column=8, row=12)
btn9 = Button(window, text="S",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn9.grid(column=9, row=12)
btn10 = Button(window, text="S",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20')) 
btn10.grid(column=10, row=12)
btn11 = Button(window, text="E",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn11.grid(column=11, row=12)
btn12 = Button(window, text="F",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn12.grid(column=12, row=12)
btn13 = Button(window, text="O",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn13.grid(column=13, row=12)
btn14 = Button(window, text="R",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn14.grid(column=14, row=12)
btn15 = Button(window, text="P",bg="yellow", fg="Black",width=3,height=1,font=('Helvetica','20'))
btn15.grid(column=15, row=12)

word_check=Entry(window,width=18,bd=2,font=('calibre','15'))
word_check.configure(highlightbackground="red", highlightcolor="red")
word_check.place(x=1010,y=200,height=25)
word_check.focus()
btncheck = Button(window, text="OK",bg="navyblue", fg="white",width=5,font=('Helvetica','10'),command=checkspells)
btncheck.place(x = 1025, y = 250)
btncheck = Button(window, text="RESET",bg="navyblue", fg="white",width=5,font=('Helvetica','10'),command=reset)
btncheck.place(x = 1155, y = 250)
label=Label(window,text="Score = 0",font=('Helvetica','15'))
label.place(x=1060, y=160)
tick()
window.after(60000, quit_pro)
window.mainloop()
